I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 68, in script call
    call mod_1
  File "game/mod.rpy", line 51, in script
    m "Hey [currentname], got a minute?"
KeyError: u'currentname'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 68, in script call
    call mod_1
  File "game/mod.rpy", line 51, in script
    m "Hey [currentname], got a minute?"
  File "renpy/ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "renpy/exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "renpy/character.py", line 1340, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "renpy/character.py", line 1254, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "renpy/character.py", line 1234, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "renpy/substitutions.py", line 278, in substitute
    s = formatter.vformat(s, (), kwargs) # type: ignore
  File "/home/tom/ab/nightly-build-fix/tmp/install.linux-x86_64/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/nightly-build-fix/tmp/install.linux-x86_64/lib/python2.7/string.py", line 585, in _vformat
  File "renpy/substitutions.py", line 168, in get_field
    obj, arg_used = super(Formatter, self).get_field(field_name, args, kwargs)
  File "/home/tom/ab/nightly-build-fix/tmp/install.linux-x86_64/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/nightly-build-fix/tmp/install.linux-x86_64/lib/python2.7/string.py", line 605, in get_value
KeyError: u'currentname'

Windows-10-10.0.19041 AMD64
Ren'Py 7.6.4.23102301+nightly
Pongers - The Mod 1.0
Thu Oct 26 19:58:21 2023
